import { cdk, SampleDir, TextFile, YamlFile } from "projen";

/**
 * Configurable knobs for Python Pixi Monorepo Project.
 */
export interface PythonPixiMonorepoProjectOptions
  extends cdk.JsiiProjectOptions {
  /**
   * What e-mail address to list for the Code of Conduct Point of Contact
   *
   * @default - `project.authorAddress`
   */
  readonly contactEmail?: string;
}

/**
 * Python Pixi Monorepo Project
 *
 */
export class PythonPixiMonorepo extends cdk.JsiiProject {
  constructor(options: PythonPixiMonorepoProjectOptions) {
    super({
      ...options,
      readme: {
        filename: "README.md",
        contents: "# Python Monorepo",
      },
      defaultReleaseBranch: "main",
      gitpod: true,
      releaseToNpm: false,
    });

    this.setupMonorepoStructure();
  }

  private setupMonorepoStructure() {
    // ---- Root configuration files ----
    new TextFile(this, ".editorconfig", {
      lines: [
        "root = true",
        "",
        "[*]",
        "end_of_line = lf",
        "insert_final_newline = true",
        "charset = utf-8",
        "indent_style = space",
        "indent_size = 2",
      ],
    });

    new TextFile(this, ".env.dev.example", {
      lines: ["# Development environment variables", "FOO=bar"],
    });

    new TextFile(this, ".envrc", {
      lines: [
        "watch_file pixi.lock",
        "",
        'PIXI_ENV="${PIXI_ENV:-default}"',
        "",
        "source_env_if_exists .envrc.local",
        "",
        'echo "Activating workspace pixi environment: $PIXI_ENV"',
        'eval "$(pixi shell-hook --environment "$PIXI_ENV" --frozen)"',
      ],
    });

    // new TextFile(this, ".gitattributes", {
    //   lines: ["* text=auto", "*.lock binary"],
    // });

    // .gitignore is usually handled by GitignoreFile component; add custom entries if needed.
    this.gitignore?.addPatterns(".envrc.local", ".env.dev", "*.pyc");

    new YamlFile(this, ".gitlab-ci.yml", {
      obj: {
        stages: ["test", "build"],
        test: {
          stage: "test",
          script: ["pixi run test"],
        },
      },
    });

    new TextFile(this, ".nvim.lua", {
      lines: [
        "-- Neovim configuration for this project",
        "vim.opt.expandtab = true",
      ],
    });

    new YamlFile(this, ".pre-commit-config.yaml", {
      obj: {
        repos: [
          {
            repo: "https://github.com/pre-commit/pre-commit-hooks",
            rev: "v4.5.0",
            hooks: [{ id: "trailing-whitespace" }, { id: "end-of-file-fixer" }],
          },
        ],
      },
    });

    new TextFile(this, "CONTRIBUTING.md", {
      lines: ["# Contributing", "Guidelines coming soon."],
    });

    new TextFile(this, "Dockerfile", {
      lines: [
        "FROM ghcr.io/prefix-dev/pixi:latest",
        "WORKDIR /app",
        "COPY . .",
        "RUN pixi install",
      ],
    });

    new TextFile(this, "Dockerfile.ci", {
      lines: [
        "FROM ghcr.io/prefix-dev/pixi:latest",
        "WORKDIR /app",
        "COPY . .",
        "RUN pixi install && pixi run lint && pixi run test",
      ],
    });

    new TextFile(this, "Makefile", {
      lines: [
        ".PHONY: help install test lint",
        "help:",
        '\t@echo "Available commands:"',
        '\t@echo "  make install   - Install dependencies with pixi"',
        '\t@echo "  make test      - Run tests"',
        '\t@echo "  make lint      - Run linters"',
        "install:",
        "\tpixi install",
        "test:",
        "\tpixi run test",
        "lint:",
        "\tpixi run lint",
      ],
    });

    new TextFile(this, "Makefile.pkg", {
      lines: ["# Additional package-specific make targets"],
    });

    // LICENSE is already generated by JsiiProject (if options.licensed is true).

    // README.md is already set in super().

    new TextFile(this, "docs/.gitignore", {
      lines: ["_build/", "*.pyc"],
    });

    new TextFile(this, "make.bat", {
      lines: ["@echo off", "pixi run %*"],
    });

    new TextFile(this, "mypy.ini", {
      lines: [
        "[mypy]",
        "python_version = 3.14",
        "warn_return_any = True",
        "warn_unused_configs = True",
      ],
    });

    // Root pixi.toml (workspace) ----
    new TextFile(this, "pixi.toml", {
      lines: [
        "[workspace]",
        'channels = ["conda-forge"]',
        'platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]',
        'preview = ["pixi-build"]',
        "",
        "[workspace.package]",
        'authors = ["DeadlySquad13"]',
        'license = "MIT"',
        "",
        "[workspace.tasks]",
        'test = "pytest"',
        'lint = "pre-commit run --all-files"',
        "",
        "[workspace.dependencies]",
        'python = "3.14.*"',
        'pytest = ">=7.0.0,<9"',
      ],
    });

    // Root pixi.lock is created by the user running `pixi install`; we can add an empty placeholder or omit it.

    new TextFile(this, "pytest.ini", {
      lines: [
        "[pytest]",
        "testpaths = packages/*/tests",
        "python_files = test_*.py",
        "python_classes = Test*",
        "python_functions = test_*",
      ],
    });

    // Sphinx source files (optional)
    new TextFile(this, "source/conf.py", {
      lines: ["# Sphinx configuration file"],
    });
    new TextFile(this, "source/index.rst", {
      lines: ["Welcome to the documentation", "============================"],
    });

    // ---- Create the two packages ----
    this.createCommonPackage();
    this.createLoggingPackage();
  }

  private createCommonPackage() {
    const pkgPath = "packages/common";

    // .envrc
    new TextFile(this, `${pkgPath}/.envrc`, {
      lines: [
        "watch_file ../../pixi.lock",
        "",
        'PIXI_ENV="${PIXI_ENV:-dsomega_common}"',
        "",
        "source_env_if_exists .envrc.local",
        "",
        'echo "Activating package pixi environment: $PIXI_ENV"',
        'eval "$(pixi shell-hook --environment "$PIXI_ENV" --manifest-path ../.. --frozen)"',
      ],
    });

    // pixi.toml
    new TextFile(this, `${pkgPath}/pixi.toml`, {
      lines: [
        "[workspace]",
        'channels = ["conda-forge"]',
        'platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]',
        'preview = ["pixi-build"]',
        "",
        "[package]",
        'name = "dsomega_common"',
        'version = "0.1.0"',
        "",
        "[package.build]",
        'backend = { name = "pixi-build-python", version = "0.*" }',
        "",
        "[package.host-dependencies]",
        'setuptools = ">=70.0.0"',
      ],
    });

    // pyproject.toml
    new TextFile(this, `${pkgPath}/pyproject.toml`, {
      lines: [
        "[build-system]",
        'requires = ["setuptools>=70.0.0", "wheel"]',
        'build-backend = "setuptools.build_meta"',
      ],
    });

    // setup.cfg
    new TextFile(this, `${pkgPath}/setup.cfg`, {
      lines: [
        "[metadata]",
        "name = dsomega_common",
        "description = Python_lib, dsomega_common utils",
        "version = 0.1.0",
        "author = DeadlySquad13",
        "license = MIT",
        "license_file = LICENSE",
        "platforms = unix, linux, osx, cygwin, win32",
        "classifiers =",
        "    Programming Language :: Python :: 3.14.0",
        "",
        "[options]",
        "packages = find:",
        "install_requires =",
        "python_requires = >=3.14",
        "package_dir =",
        "    =src",
        "zip_safe = no",
        "",
        "[options.packages.find]",
        "where=src",
        "",
        "[options.package_data]",
        "find = py.typed",
        "",
        "[flake8]",
        "max-line-length = 100",
      ],
    });

    // Source files
    new SampleDir(this, `${pkgPath}/src/hello_world`, {
      files: {
        "__init__.py": "",
        "main.py": [
          "import logging",
          "from rich.logging import RichHandler",
          "",
          "def hello_world():",
          '    """Generate a greeting message.',
          "",
          "    This function returns a simple greeting string that can be used",
          "    as a starting point for the application.",
          "",
          "    :return: A greeting message string",
          "    :rtype: str",
          '    """',
          '    log = logging.getLogger("test")',
          "    log.addHandler(RichHandler())",
          '    log.info("test")',
          "    return 'Hello World!'",
          "",
          "",
          'if __name__ == "__main__":',
          "    result = hello_world()",
          "    print(result)",
        ].join("\n"),
      },
    });

    // Tests
    new SampleDir(this, `${pkgPath}/tests`, {
      files: {
        "__init__.py": "",
        "test_hello_world.py": [
          "from hello_world.main import hello_world",
          "",
          "",
          "def test_hellow_world():",
          '    assert hello_world() == "Hello World!"',
        ].join("\n"),
      },
    });
  }

  private createLoggingPackage() {
    const pkgPath = "packages/logging";

    // .envrc
    new TextFile(this, `${pkgPath}/.envrc`, {
      lines: [
        "watch_file ../../pixi.lock",
        "",
        'PIXI_ENV="${PIXI_ENV:-dsomega_logging}"',
        "",
        "source_env_if_exists .envrc.local",
        "",
        'echo "Activating package pixi environment: $PIXI_ENV"',
        'eval "$(pixi shell-hook --environment "$PIXI_ENV" --manifest-path ../.. --frozen)"',
      ],
    });

    // // .gitattributes
    // new TextFile(this, `${pkgPath}/.gitattributes`, {
    //   lines: ["* text=auto"],
    // });

    // .gitignore
    new TextFile(this, `${pkgPath}/.gitignore`, {
      lines: ["__pycache__/", "*.pyc", ".envrc.local"],
    });

    // pixi.toml
    new TextFile(this, `${pkgPath}/pixi.toml`, {
      lines: [
        "[workspace]",
        'channels = ["conda-forge"]',
        'platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]',
        'preview = ["pixi-build"]',
        "",
        "[package]",
        'name = "dsomega_logging"',
        'version = "0.1.0"',
        "",
        "[package.build]",
        'backend = { name = "pixi-build-python", version = "0.*" }',
        "",
        "[package.host-dependencies]",
        'setuptools = ">=70.0.0"',
      ],
    });

    // pyproject.toml
    new TextFile(this, `${pkgPath}/pyproject.toml`, {
      lines: [
        "[build-system]",
        'requires = ["setuptools>=70.0.0", "wheel"]',
        'build-backend = "setuptools.build_meta"',
      ],
    });

    // setup.cfg
    new TextFile(this, `${pkgPath}/setup.cfg`, {
      lines: [
        "[metadata]",
        "name = dsomega_logging",
        "description = Python logging utilities",
        "version = 0.1.0",
        "author = DeadlySquad13",
        "license = MIT",
        "license_file = LICENSE",
        "platforms = unix, linux, osx, cygwin, win32",
        "classifiers =",
        "    Programming Language :: Python :: 3.14.0",
        "",
        "[options]",
        "packages = find:",
        "install_requires =",
        "    rich>=13.0.0",
        "python_requires = >=3.14",
        "package_dir =",
        "    =src",
        "zip_safe = no",
        "",
        "[options.packages.find]",
        "where=src",
        "",
        "[options.package_data]",
        "find = py.typed",
        "",
        "[flake8]",
        "max-line-length = 100",
      ],
    });

    // Source files
    new SampleDir(this, `${pkgPath}/src/dsomega_logging`, {
      files: {
        "__init__.py": "",
        "console.py": [
          "import logging",
          "from rich.console import Console",
          "from rich.logging import RichHandler",
          "",
          "def setup_rich_logging():",
          "    console = Console()",
          "    logging.basicConfig(",
          "        level=logging.INFO,",
          '        format="%(message)s",',
          "        handlers=[RichHandler(console=console)]",
          "    )",
        ].join("\n"),
        "main.py": [
          "from datetime import datetime",
          "import logging",
          "",
          "def date_iso() -> str:",
          '    """Return current date in ISO format."""',
          "    return datetime.now().isoformat()",
          "",
          "",
          "def get_logger(name: str):",
          '    """Get a logger with the given name."""',
          "    return logging.getLogger(name)",
        ].join("\n"),
      },
    });
  }
}
